version: "3.8"

services:
  app:
    build: .
    container_name: produtivix-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules  # Impede conflitos entre node_modules local e do container